name: Release

on:
  workflow_run:
    workflows: [Validate]
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VOLTA_FEATURE_PNPM: 1
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build_internal

      - name: Release package
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
