name: Validate and Release

on: 
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16, 18]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node and yarn
        uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
