name: Validate

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      VOLTA_FEATURE_PNPM: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build_internal

      - name: Validate package
        run: pnpm validate

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-build
          path: dist/
