name: Validate and Release

on: 
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18.18.0]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Enables corepack
        run: corepack enable

      - name: Set up yarn version
        run: yarn set version 3.6.3

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
