name: Validate and Release

on: 
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18.18.0]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build_internal

      - name: Validate package
        run: yarn validate

      - name: Print credentials
        run: echo ${{ secrets.GH_TOKEN }}

      - name: Release package
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          debug: true
        env:
          GH_TOKEN: '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'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
