name: Validate and Release

on: 
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [21.0.0]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup volta
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: volta install node
        run: volta install pnpm

      - name: Build package
        run: pnpm build_internal

      - name: Validate package
        run: pnpm validate

      - name: Release package
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
