name: Validate and Release

on: 
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16, 18]
        yarn: [3.6.3]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install yarn
        run: npm install -g yarn@3.6.3

      - name: Install yarn workspaces plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
